<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-GLAJOS1C" failures="1" tests="2" name="runner.FailedRunner" time="71.407" errors="0" timestamp="2025-10-25T12:17:48 IST" skipped="0">
  <testcase classname="runner.FailedRunner" name="runScenario" time="56.083"/>
  <testcase classname="runner.FailedRunner" name="runScenario" time="15.324">
    <failure message="expected [7] but found [5]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [7] but found [5]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at org.testng.Assert.assertEquals(Assert.java:1441)
at stepDefinitions.CommonStepsElements.userintentionallyfailedtestcase(CommonStepsElements.java:71)
at âœ½.user intentionally failed test case(file:///C:/WorkspaceSeleniumUI/selniumUIProject/src/test/resources/features/Elements.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runner.FailedRunner -->
